### ISSUE TITLE
spectacular: The pipe testing harness doesn't work with Angular >=13.1

### ISSUE THREAD

**Issue by LayZeeDK** [ngworker/ngworker#38]
## Describe the bug

`PipeResolver` is used internally by Spectacular 0.3.0 but is [removed in Angular 13.1](https://github.com/angular/angular/pull/44368).

## To Reproduce

1. Install Angular 13.1.0.
2. Install Spectacular.
3. Create pipe harness.
4. Test fails due to compilation error.

## Expected behavior

1. Install Angular 13.1.0.
2. Install Spectacular.
3. Create pipe harness.
4. Test passes.

## Additional context

Reported by @dzhavat.
